services:
  - name: docker:dind

variables:
  DOCKER_DRIVER: overlay2  
  DOCKER_TLS_CERTDIR: ""


cache:
    paths:
        - .m2/repository/
        - target/

stages:
  - deploy
  - builddocker

deploy:
    image: maven:latest
    stage: deploy
    script:
        - mvn package
        - cp target/spring-boot-web-socket-0.0.1-SNAPSHOT.jar ./springbootwebsocketdemo.jar
        - ls -la
    tags: 
        - myrunner
    only:
        - master
    artifacts:
        paths:
            - target\spring-boot-web-socket-0.0.1-SNAPSHOT.jar

builddocker:
    image: docker:latest
    stage: builddocker
    script:
      - ls -la
      - echo "$LOCAL_REGISTRY" | docker login -u tuttas --password-stdin
      - docker build -t tuttas/springbootwebsocketdemoapplication .
      - docker push tuttas/springbootwebsocketdemoapplication
    dependencies: 
        - deploy
    tags: 
        - myrunner
    only:
        - master
