services:
  - name: docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2  
  DOCKER_TLS_CERTDIR: ""


cache:
    paths:
        - .m2/repository/
        - target/

stages:
  - deploy
  - builddocker

deploy:
    image: maven:latest
    stage: deploy
    script:
        - mvn package
    tags: 
        - myrunner
    only:
        - master
    artifacts:
        paths:
            - target\spring-boot-web-socket-0.0.1-SNAPSHOT.jar

builddocker:
    image: docker:latest
    stage: builddocker
    script:
      - echo "$LOCAL_REGISTRY" | docker login -u root --password-stdin service.joerg-tuttas.de:5555
      - docker build -t service.joerg-tuttas.de:5555/root/springbootwebsocketdemoapplication .
      - docker push service.joerg-tuttas.de:5555/root/springbootwebsocketdemoapplication
    dependencies: 
        - deploy
    tags: 
        - myrunner
    only:
        - master
