name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: list files
        run: 'ls -laR'
      - name: Cache files 
        uses: actions/cache@v2
        env:
          cache-name: cache-files
        with:
          path: | 
            ./target
            .
          key: $build-${{ env.cache-name }}-${{ github.event.head_commit.message }}
    

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cache files 
        uses: actions/cache@v2
        env:
          cache-name: cache-files
        with:
          path: | 
            ./target
            .
          key: $build2-${{ env.cache-name }}-${{ github.event.head_commit.message }}
          restore-keys: |
            $build-${{ env.cache-name }}-${{ github.event.head_commit.message }}
      - name: list files
        run: 'ls -laR'
      - name: copy file
        run: 'cp ./target/spring-boot-web-socket-0.0.1-SNAPSHOT.jar springbootwebsocketdemo.jar'        
      - name: list files
        run: 'ls -la'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tuttas/webchat:latest